[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/portfolio-0.0.1-SNAPSHOT.jar"
