[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["cd mariana-portfolio/backend && mvn clean package -DskipTests"]

[phases.start]
cmd = "cd mariana-portfolio/backend && java -jar target/portfolio-0.0.1-SNAPSHOT.jar"
