[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.install]
cmds = ["./build.sh"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd mariana-portfolio/backend && java -jar target/portfolio-0.0.1-SNAPSHOT.jar"

[providers]
java = "21"
